import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Moodle Web Services API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="flex h-screen w-screen flex-col overflow-hidden">
            {children}
            <footer className="flex h-10 shrink-0 items-center justify-center border-t bg-muted/40 px-4">
              <span className="text-sm text-muted-foreground">
                Made with 💖 by{" "}
                <a
                  href="https://github.com/yassine-safraoui"
                  className="hover:underline hover:underline-offset-2"
                >
                  Yassine Safraoui
                </a>{" "}
                © {new Date().getFullYear()} LIG
              </span>
            </footer>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
